// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoviRaspored.Models;

namespace NoviRaspored.Migrations
{
    [DbContext(typeof(ZadatakContext))]
    partial class ZadatakContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NoviRaspored.Models.Zadatak", b =>
                {
                    b.Property<int>("zadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Dan")
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Vreme")
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("zadId");

                    b.ToTable("Rasporeds");
                });
#pragma warning restore 612, 618
        }
    }
}
